server.forward-headers-strategy=framework
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
spring.devtools.add-properties=false
aws.bucket.name=${USER_FILES_BUCKET}
aws.bucket.region=ap-south-1
aws.dynamodb.table.name=${DYNAMO_TABLE}
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=6379
spring.data.redis.ssl.enabled=true
spring.data.redis.password=${REDIS_AUTH_TOKEN}