server.forward-headers-strategy=framework
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
spring.devtools.add-properties=false
spring.datasource.username=
spring.datasource.password=
spring.datasource.url=
aws.bucket.name=
aws.bucket.region=
spring.data.redis.host=
spring.data.redis.port=