spring.datasource.username=app
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://localhost:5432/mint

aws.bucket.name=fs.mint.bucket.test
aws.bucket.region=ap-south-1
spring.data.redis.url=redis://redis:6379

allowed.cors.origin=http://localhost:5173