spring.datasource.url=jdbc:postgresql://localhost:5432/mint
spring.datasource.username=app
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
aws.bucket.name=fs.mint.bucket.test
aws.bucket.region=ap-south-1
spring.data.redis.host=localhost
spring.data.redis.port=6379