spring.application.name=mint

spring.datasource.url=jdbc:postgresql://localhost:5432/mint
spring.datasource.username=app
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create

spring.jpa.open-in-view=false
aws.bucket.name=bucket-name
aws.bucket.region=ap-south-1