spring.application.name=mint

spring.datasource.url=jdbc:postgresql://localhost:5432/mint
spring.datasource.username=app
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false