name: backend-cd

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["backend/**"]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  # run-ci:
  #   uses: ./.github/workflows/backend-ci.yml

  build-push:
    runs-on: ubuntu-latest
    # needs: run-ci
    outputs:
      image-tag: ${{ steps.tags.outputs.COMMIT_TAG }}
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Files
        uses: actions/checkout@v7

      - name: Setup Docker
        uses: docker/setup-docker-action@v5.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login Docker
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Image Tags
        id: tags
        run: |
          REPO_OWNER="${{ github.repository_owner }}"
          LOWERCASE_REPO_OWNER="${REPO_OWNER,,}"
          echo "COMMIT_TAG=ghcr.io/$LOWERCASE_REPO_OWNER/mint-backend:${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "LATEST_TAG=ghcr.io/$LOWERCASE_REPO_OWNER/mint-backend:latest" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          context: backend
          tags: |
            ${{ steps.tags.outputs.COMMIT_TAG }}
            ${{ steps.tags.outputs.LATEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  redeploy:
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      - uses: actions/checkout@v7
        name: Pull Files

      - name: Create .env
        run: |
          echo "IMAGE_TAG=${{ needs.build-push.outputs.image-tag }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST= ${{ vars.RDS_ENDPOINT }}" >> .env

      - name: Upload Compose file
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: admin
          key: ${{ secrets.SSH_KEY }}
          source: "backend/docker-compose.prod.yml"
          target: "/tmp/config"
          overwrite: true
          strip_components: 1

      - name: Upload application properties
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: admin
          key: ${{ secrets.SSH_KEY }}
          source: "backend/src/main/resources/application.properties,backend/src/main/resources/application-prod.properties"
          target: "/tmp/config"
          overwrite: true
          strip_components: 4

      - name: Deploy backend
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE_TAG: ${{ needs.build-push.outputs.image-tag }}
          DB_HOST: ${{ vars.RDS_ENDPOINT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: admin
          key: ${{ secrets.SSH_KEY }}
          envs: IMAGE_TAG,DB_HOST,DB_USERNAME,DB_PASSWORD
          script: |
            sudo cp -r /tmp/config /opt/mint-backend/
            sudo docker compose -f /opt/mint-backend/config/docker-compose.prod.yml pull
            sudo docker compose -f /opt/mint-backend/config/docker-compose.prod.yml up -d