name: backend-ci

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: "backend/**"
  pull_request:
    branches: [main]
    paths: "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v7
        name: Pull Files
      - uses: actions/setup-java@v5
        name: Setup Java
        with:
          java-version: "21"
          distribution: "temurin"
      - uses: actions/cache@v6
        name: Warm Cache
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
      - name: Run Tests
        run: mvn clean test
      - name: Build Backend
        run: mvn clean package -DskipTests
