name: create-app

on:
  workflow_dispatch:

concurrency:
  group: fast-deploy-single-ec2-lifecycle
  cancel-in-progress: false

jobs:
  infra-cd:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/infra-cd.yml
    secrets: inherit

  backend-cd:
    needs: infra-cd
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/backend-cd.yml
    with:
      APP_HOST: ${{ needs.infra-cd.outputs.APP_HOST }}
    secrets: inherit
