name: create-app

on:
  workflow_dispatch:

jobs:
  infra-cd:
    uses: ./.github/workflows/infra-cd.yml
    
  frontend-cd:
    needs: infra-cd
    uses: ./.github/workflows/frontend-cd.yml

  backend-cd:
    needs: infra-cd
    uses: ./.github/workflows/backend-cd.yml
  