name: destroy-app

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type fast-deploy-single-ec2 to confirm"
        required: true
        type: string

permissions:
  contents: read
  id-token: write

concurrency:
  group: fast-deploy-single-ec2-lifecycle
  cancel-in-progress: false

jobs:
  destroy:
    if: inputs.confirm == 'fast-deploy-single-ec2'
    environment: fast-deploy-single-ec2
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: fast-deploy-single-ec2
    defaults:
      run:
        working-directory: ./infra

    steps:
      - uses: actions/checkout@v7

      - name: Setup AWS and Terraform
        uses: ./.github/actions/setup-aws-terraform
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ vars.INFRA_ROLE_ARN }}
          working-directory: "./infra"
          environment: ${{ env.ENVIRONMENT }}

      - name: Terraform Destroy
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        run: terraform destroy -no-color -input=false -auto-approve -var-file="envs/$ENVIRONMENT.tfvars"

      - name: Delete Environment Variables
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: gh variable delete APP_HOST --env "$ENVIRONMENT" || true
