name: frontend-cd

on:
  workflow_call:
    inputs:
      CLOUDFRONT_ID:
        type: string
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["frontend/**"]

permissions:
  contents: read
  id-token: write

jobs:
  run-ci:
    uses: ./.github/workflows/frontend-ci.yml

  deploy:
    needs: run-ci
    runs-on: ubuntu-latest

    steps:
      - name: Download build
        uses: actions/download-artifact@v8.0.0
        with:
          artifact-ids: ${{ needs.run-ci.outputs.build-id }}
          path: /tmp/build

      - uses: aws-actions/configure-aws-credentials@v6
        name: Configure AWS Credentials
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ vars.DEPLOY_ROLE_ARN }}

      - name: Sync S3
        run: |
          aws s3 sync /tmp/build s3://mint-frontend-bucket/ --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ inputs.CLOUDFRONT_ID || vars.CLOUDFRONT_ID }} --path /index.html
