name: frontend-ci

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["frontend/**"]
  pull_request:
    branches: [main]
    paths: ["frontend/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v7
        name: Checkout Files
      - uses: actions/setup-node@v7
        name: Setup Node
        with:
          node-version: "26.1.0"
      - uses: actions/cache@v6
        name: Warmup Cache
        with:
          path: ~/.npm
          key: nodejs-${{ hashFiles('**/package-lock.json') }}
          restore-keys: nodejs-
      - name: Install Dependencies
        run: npm ci
      - name: Lint Checks
        run: npm run lint
      - name: Run Tests
        run: npm test
      - name: Build Frontend
        run: npm run build
