name: infra-ci

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["infra/**"]
  pull_request:
    branches: [main]
    paths: ["infra/**"]

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
        
    steps:
      - uses: actions/checkout@v7
        name: Checkout Files
      - uses: aws-actions/configure-aws-credentials@v6
        name: Configure AWS Credentials
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ vars.INFRA_ROLE_ARN }}
      - run: aws sts get-caller-identity