name: test-ssh

on:
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: admin
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo ls /tmp/
